$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: deployment
endpoint_name: ep-mlops
model:
  name: lr-mlops
  version: 1
  path: azureml://subscriptions/${{secrets.AZURE_SUBSCRIPTION_ID}}/resourcegroups/rg-mlops/workspaces/ws-mlops/datastores/workspaceartifactstore/paths/ExperimentRun/dcid.dynamic_pencil_y1hqrrhfm5/model
  type: mlflow_model
# model: azureml:my-model:@latest
# environment: azureml:model-evaluation:@latest
instance_type: Standard_E2s_v3
instance_count: 1
