name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Clone repo
      run: git clone https://github.com/j4nb00n/mslearn-mlops rp-mlops
    - name: Create compute cluster
      run: az ml compute create --name "cc-mlops" --size STANDARD_DS11_V2 --max-instances 2 --type AmlCompute --resource-group rg-mlops --workspace-name ws-mlops
    - name: Manually trigger job
      run: az ml job create --file ./rp-mlops/src/job.yml --resource-group rg-mlops --workspace-name ws-mlops
